### ISSUE TITLE
Reset Level back to PRO (default) after a try

### ISSUE THREAD

**Issue by jabranr** [jabranr/guess-where#9]
Currently once Level is changed from default, it keeps on loading new maps with that verbose Level. It should reset back to default so the game remains interesting and guess-able.

Example:

![image](https://user-images.githubusercontent.com/2131246/66739742-3e8e4a00-ee69-11e9-8b8f-7d389a472f58.png)

**Comment by brendon1555** [comment]
I can give this a go

**Comment by jabranr** [comment]
Thank you @brendon1555 for picking it up! 👍🏼

**Comment by jabranr** [comment]
Fixed as part of #10
